BookStore Styles
luccamicale/bookstore pull request #5
Opened 2022-11-17 22:23 UTC by luccamicale

## I added the styles in my BookStore 💯 👍 

##https://github.com/luccamicale/bookstore 🥇 

## Checklist before requesting a review 💯 🔢 
- [ ] I have performed a self-review of my code
- [ ] I follow the instructions about styles
- [ ] I understood how to implement different styles
- [ ] I keep my code very tidy and clean 👍

2022-11-17 22:49 UTC, tufoinnkuo10 reviewed
Hi @luccamicale 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-11-17 22:49 UTC, tufoinnkuo10 commented on src/modules-css/addbook.css
> +  width: 91.3%;
- [ ] great job.the add book title and author is not visible as it is right down and kind of hiden. please increase the bottom margin so it follows the zeplin design.
![Screenshot (592)_LI](https://user-images.githubusercontent.com/65298048/202576365-3be9ec76-1afc-4ac7-a317-4e751cdb9a27.jpg)

2022-11-17 22:52 UTC, tufoinnkuo10 requested changes
Hi @luccamicale 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-11-17 23:31 UTC, luccamicale commented
I modified the change that ask me the last reviewer. Now My project is complete and perfect!!!
It should be approved!! 💯

2022-11-18 00:09 UTC, BenMukebo approved these changes
### Hi @luccamicale, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- No Linter errors :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- The README file It is the first file a person will see when they encounter your project, so it should be fairly brief but detailed. It will make your project stand out from a bunch of others.
- [OPTIONAL] It will be nice to add explicit steps to clone and run your project locally, as this will be of help to non-technical users. Please add descriptive steps from cloning your app to seeing the results displayed on the browser.. This includes `git clone URL` , `cd project_name`,  `npm install`, `npm start`, etc 🙃 


- [OPTIONAL] When I click the link to the `MIT.md` file that you added, I get this 404 `error`:

![00Mit](https://user-images.githubusercontent.com/79058364/182822618-fdfb2523-cb23-4060-9f72-75ec8c29e4cd.png)


#### The reason for this is that there is no `MIT.md` file in the root directory of this project. Kindly attach the file. 👍

- [OPTIONAL] The styling has to be EXACTLY the same as the one provided on [Zeplin](https://zeplin.io/). Please add the missing vertical bars ✍🏻 

![333](https://user-images.githubusercontent.com/79058364/202586987-af2db97c-0361-4f34-b7b4-ad28125cefa1.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-18 01:30 UTC, merged